-- CreateEnum
CREATE TYPE "TenantMode" AS ENUM ('WHITE_LABEL', 'MIXED', 'MULTI_VENDOR', 'MARKETPLACE');

-- AlterTable
ALTER TABLE "Tenant" ADD COLUMN     "mode" "TenantMode" NOT NULL DEFAULT 'WHITE_LABEL';
